'use client';

import { useState, useEffect } from 'react';
import { apiClient, Receipt } from '@/lib/api';
import jsPDF from 'jspdf';

export default function ReceiptsPage() {
    const [receipts, setReceipts] = useState<Receipt[]>([]);
    const [loading, setLoading] = useState(true);
    const [filter, setFilter] = useState<'all' | 'accepted' | 'rejected'>('all');

    useEffect(() => {
        fetchReceipts();
    }, [filter]);

    const fetchReceipts = async () => {
        try {
            setLoading(true);
            const data = await apiClient.getReceipts(filter === 'all' ? undefined : filter);
            setReceipts(data);
        } catch (error) {
            console.error('Error fetching receipts:', error);
        } finally {
            setLoading(false);
        }
    };

    const downloadReceiptPDF = (receipt: Receipt) => {
        const pdf = new jsPDF();
        const pageWidth = pdf.internal.pageSize.getWidth();
        let yPosition = 20;

        // Header
        pdf.setFontSize(20);
        pdf.setFont('helvetica', 'bold');
        pdf.text(`${receipt.receipt_type.toUpperCase()} Items Receipt`, pageWidth / 2, yPosition, { align: 'center' });
        yPosition += 15;

        // Receipt Info
        pdf.setFontSize(12);
        pdf.setFont('helvetica', 'normal');
        pdf.text(`Receipt Number: ${receipt.receipt_number}`, pageWidth / 2, yPosition, { align: 'center' });
        yPosition += 10;
        pdf.text(`Date: ${new Date(receipt.created_at).toLocaleDateString()}`, pageWidth / 2, yPosition, { align: 'center' });
        yPosition += 15;

        // Receipt Details
        pdf.setFont('helvetica', 'bold');
        pdf.text('Receipt Information:', 20, yPosition);
        yPosition += 8;
        pdf.setFont('helvetica', 'normal');
        pdf.text(`Type: ${receipt.receipt_type.toUpperCase()}`, 30, yPosition);
        yPosition += 6;
        pdf.text(`Generated By: ${receipt.generated_by}`, 30, yPosition);
        yPosition += 6;
        pdf.text(`Generated Date: ${new Date(receipt.generated_date).toLocaleDateString()}`, 30, yPosition);
        yPosition += 15;

        // Summary
        pdf.setFont('helvetica', 'bold');
        pdf.text('Summary:', 20, yPosition);
        yPosition += 8;
        pdf.setFont('helvetica', 'normal');
        pdf.text(`Total Quantity: ${receipt.total_quantity}`, 30, yPosition);
        yPosition += 6;
        pdf.text(`Total Price: ${receipt.total_value.toLocaleString()}`, 30, yPosition);
        yPosition += 15;

        // Remarks
        if (receipt.remarks) {
            pdf.setFont('helvetica', 'bold');
            pdf.text('Remarks:', 20, yPosition);
            yPosition += 8;
            pdf.setFont('helvetica', 'normal');
            const remarksLines = pdf.splitTextToSize(receipt.remarks, 170);
            remarksLines.forEach((line: string) => {
                pdf.text(line, 30, yPosition);
                yPosition += 5;
            });
        }

        // Save PDF
        const fileName = `${receipt.receipt_type.toUpperCase()}_Receipt_${receipt.receipt_number}_${new Date(receipt.created_at).toISOString().slice(0,10)}.pdf`;
        pdf.save(fileName);
    };

    return (
        <div className="animate-fade-in">
            <div className="flex justify-between items-center mb-8">
                <div>
                    <h1 className="text-4xl font-bold mb-2 bg-gradient-to-r from-orange-600 to-red-600 bg-clip-text text-transparent">
                        Receipts
                    </h1>
                    <p className="text-gray-600">Generated receipts for accepted and rejected items</p>
                </div>
            </div>

            {/* Filters */}
            <div className="card mb-6">
                <div className="flex gap-4">
                    <button
                        onClick={() => setFilter('all')}
                        className={`btn ${filter === 'all' ? 'btn-primary' : 'bg-gray-200 text-gray-700'}`}
                    >
                        All Receipts
                    </button>
                    <button
                        onClick={() => setFilter('accepted')}
                        className={`btn ${filter === 'accepted' ? 'btn-success' : 'bg-gray-200 text-gray-700'}`}
                    >
                        Accepted
                    </button>
                    <button
                        onClick={() => setFilter('rejected')}
                        className={`btn ${filter === 'rejected' ? 'btn-danger' : 'bg-gray-200 text-gray-700'}`}
                    >
                        Rejected
                    </button>
                </div>
            </div>

            {loading ? (
                <div className="card text-center py-12">
                    <div className="text-4xl mb-4">⏳</div>
                    <p className="text-gray-600">Loading receipts...</p>
                </div>
            ) : receipts.length === 0 ? (
                <div className="card text-center py-12">
                    <div className="text-6xl mb-4">🧾</div>
                    <h3 className="text-xl font-semibold mb-2">No receipts found</h3>
                    <p className="text-gray-600 mb-6">Receipts will appear here after generation</p>
                </div>
            ) : (
                <div className="grid gap-6">
                    {receipts.map((receipt) => (
                        <div key={receipt.id} className="card hover:shadow-md transition-shadow">
                            <div className="flex flex-col md:flex-row justify-between gap-4">
                                <div>
                                    <div className="flex items-center gap-3 mb-2">
                                        <h3 className="text-xl font-bold">{receipt.receipt_number}</h3>
                                        <span className={`badge ${receipt.receipt_type === 'accepted' ? 'badge-success' : 'badge-danger'}`}>
                                            {receipt.receipt_type.toUpperCase()}
                                        </span>
                                    </div>
                                    <p className="text-gray-600 mb-1">
                                        <span className="font-medium">Generated By:</span> {receipt.generated_by}
                                    </p>
                                    <p className="text-gray-600">
                                        <span className="font-medium">Date:</span> {new Date(receipt.created_at).toLocaleDateString()}
                                    </p>
                                    {receipt.remarks && (
                                        <p className="text-gray-500 text-sm mt-2 italic">"{receipt.remarks}"</p>
                                    )}
                                </div>

                                <div className="flex flex-col items-end justify-center">
                                    <div className="text-right mb-2">
                                        <p className="text-sm text-gray-500">Total Quantity</p>
                                        <p className="text-xl font-bold">{receipt.total_quantity}</p>
                                    </div>
                                    <div className="text-right mb-3">
                                        <p className="text-sm text-gray-500">Total Price</p>
                                        <p className="text-xl font-bold text-blue-600">
                                            {receipt.total_value.toLocaleString()}
                                        </p>
                                    </div>
                                    <button
                                        onClick={() => downloadReceiptPDF(receipt)}
                                        className="btn bg-gray-100 hover:bg-gray-200 text-gray-700 text-sm"
                                    >
                                        📄 Download PDF
                                    </button>
                                </div>
                            </div>
                        </div>
                    ))}
                </div>
            )}
        </div>
    );
}
